name : ci

on:
  push:
    branches:
      - master

jobs:
  lint: 
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint go code
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.30

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Test code
        run: go test -v ./... 
